### ISSUE TITLE
[Suggestion] Scalable bottle creation cost.

### ISSUE THREAD

**Issue by MortalRaven** [CodedRed-Spigot/XpBottles#17]
Hello.
Players on my server repeatedly ask me to increase the limits in bottles but I don't want to allow it at the currently low cost (economy).
I thought of two ways to solve this problem.

1. Possibility to set different cost for different ranges of taken experience. Something like this:
```
  cost1:
    min-bottle-amount: 50.0
    max-bottle-amount: 1000.0
    cost: 500
  cost2:
    min-bottle-amount: 1001.0
    max-bottle-amount: 5000.0
    cost: 1000
```

2. Cost as a percentage of experience taken. For example if player wants to create bottle with 1000 exp, and percentage cost is set to 20% it would take 200$ from player account. This one would be even better than first option.
```
  cost:
    enabled: true
        flat-cost: false
            amount: 300
        percentage-cost: true
            amount: 30
```

It would be really nice if you could add any of these to plugin.
